# wrangler.toml
# Cloudflare Workers 项目配置文件

name = "inft"
main = "worker.js"
compatibility_date = "2025-10-25"
workers_dev = true
node_compat = false

[[kv_namespaces]]
binding = "PROFILES_KV"
id = "PROFILES_KV"

# 可选变量
# [vars]
# ENV = "production"
